In [1]:
import numpy as np
from numpy.linalg import inv
import matplotlib
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
plt.style.use('ggplot')

In [2]:
def dataset_ (N=200, idx_outlier=0, ydistance=5):
    rng = np.random.RandomState(4)
    data  = np.dot(rng.rand(2, 2), rng.randn(2, N)).T
    data[idx_outlier:idx_outlier+1,1] = ydistance
    return data

In [3]:
N=50
inx=10
i = dataset_(N, inx)
Z = i[:,0].reshape(len(i[:,0]),1)
y = i[:,1].reshape(len(i[:,1]),1)
b = lambda Z,y: inv(np.dot(Z.T,Z)).dot(Z.T).dot(y)
ypred = lambda Z,b: Z.dot(b)

In [4]:
original_ypred = ypred(Z, b(Z,y))
p = len(i.T)-1
s2 = mean_squared_error(y, original_ypred)

In [5]:
outliers,Ds = [],[]
for n in range(N):
    #without i-th obeservation
    tempZ = np.delete(Z, (n), axis=0)
    tempY = np.delete(y, (n), axis=0)
    tempB = b(tempZ, tempY)
    tempYPred = ypred(tempZ, tempB)
    #get rid of i-th observation from oritinal predition too
    original_YPred_ = np.delete(original_ypred, (n), axis=0)
    
    errs = sum((original_YPred_ - tempYPred)**2)
    D = errs/(p*s2)
    Ds.append(D)
    if D[0] > .1: 
        outliers.append(n)

In [6]:
Ds.sort(reverse=True);Ds[:5]

[array([0.1488515]),
 array([0.00753585]),
 array([0.00690743]),
 array([0.00671447]),
 array([0.0046191])]

In [7]:
outliers

[10]